services:
  - type: web
    name: secure-image-encryption-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_SECRET_KEY
        value: qwertyuiopasdfghjklzxcvbnm1234567890
      - key: DEBUG
        value: False
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
