services:
  - type: web
    name: secure-image-encryption-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_SECRET_KEY
        value: qwertyuiopasdfghjklzxcvbnm1234567890
      - key: DEBUG
        value: False
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
